language: cpp
sudo: true
dist: trusty

compiler:
    - g++

#Build steps
before_install:
    - sudo apt-get install libsdl2-dev -y

script:
    - ./autogen.sh
    - ./configure
    - make

after_failure:
    - cat config.log
